language: node_js

node_js:
  - "9"

cache:
  apt: true
  directories:
    - node_modules

addons:
  apt:
    packages:
      - graphicsmagick

env:
  matrix:
    - CXX=g++-4.8
  global:
    - secure: "gPiE5CHXO4ZJyn4+mc4A/bKsIhYgAry+38ov3kECXUacIQ7mmvIFozyJ2mlcgg6+6RkgqFEk7vRLIYaThqNJhlP79GYgRms4SM1VTfK/3NMEv4rz5kc0qURPNoOhsMEC4PlkMLybrINAVwxn4XcXB1Ng5dF8s4JKqkr8gBWtNj3kxZyQjR21h4NIx27K4MwmobH9PAPvf8tjdDsbXN8O3zU2zQsu81LjyGVqBYbFZACrJifQsLxFTAiPD+zsh4lXvddgURQ/5wztxeFt3aIsf8fm9nLGTxovh7egd7DfJBA2hwwawL2bNXdquaD8b+Q6h7hKWg1hhuIXP/ylmEW5A03cWWJalw0wDzjXBCPjmdMgjfLgwba8H84OTrNlxBqzIhGZPV4tGfFrAkmlxFNd0etCoq93w1HwIifYhH1u6Xws8jeAP2NKC9bVjAsPGwcTOBLQfy0f/GL8hZM5lDg98KFtF0rzd0VjeT0Lh8Ojfbjbskd4AWMK+S9/6DlNU9WguAa1J50IqqbbkaKxWXr0c4tMB4nweTfV/Rrmkg+jC8Bc8lejnstJDieGiTTmJG/tCEMBqwOYVjhYJm54Nf4yi0EFC/65Mp/PIN/nZ6ASZ4KfR4homaFHWG+R8Wav0u7ZGExED9xI3YO4j0v/xXahBAzlUFtRu48Oha9czG/K+bg="
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  ssh_known_hosts: github.com

before_install:
  # Set Git config
  - git config --global user.name "meolu"
  - git config --global user.email "wushuiyong@huamanshu.com"
  # - git config --global push.default simple
  # - NODEJS_ORG_MIRROR=https://npm.taobao.org/mirrors/node nvm install 9
  # - rm -rf $HOME/.node-gyp
  # - npm cache clean -f
  # - npm install npm -g
  # - npm uninstall node-gyp -g
  # - npm install sharp --save

install:
  - npm install

script:
  # Clone the repository
  - git clone https://${GH_TOKEN}@github.com/meolu/walle-web.io.git .deploy_git -v
  # Update docs.
  - git --version
  # - git remote add -f docs https://${GH_TOKEN}@github.com/meolu/doc.git
  # - git fetch docs
  # - git subtree add --prefix=source/docs/en docs/en --squash
  # - git subtree add --prefix=source/docs/zh-cn docs/zh-cn --squash
  # Install dependencies
  - mv -f walle-web.io/* source/
  # - npm install --no-optional

after_script:
  - hexo generate && gulp
  - cd .deploy_git
  - git rm -r *
  - git commit -am "remove"
  - cd ..
  - cp -rf public/docs/1/zh-cn/* public/docs/1/
  - cp -rf public/docs/2/zh-cn/* public/docs/2/
  - cp -rf public/docs/2/* public/docs/
  - cp -rf public/* .deploy_git/
  - cd .deploy_git
  - git add -A
  - git commit -am "Auto deploy from Travis-CI."
  - git push --force

branches:
  only:
    - master
